### ISSUE TITLE
Wrong links in readme

### ISSUE THREAD

**Issue by ruv** [nnCron/nnCron#10]
https://github.com/nnCron/nnCron/blob/ada4e9d6e89c3710b56e94ea8b9101bc908ab7a3/README.md?plain=1#L8-L10

The website at `http://www.nncron.ru` does not work. These links should probably be `https://nncron.ru` (without the `www.` prefix).

**Comment by VoidVolker** [comment]
Thanx for report! Urls is correct and was working several days ago. And last few days website have some issues and I'll try to figure it out.

**Comment by ruv** [comment]
For example:
  - http://www.nncron.ru/forums/  — does not work (error 404 — not found).
  - https://nncron.ru/forums/ — works.
