### ISSUE TITLE
[Question] Как установить периодический запуск .bat-файла с правами администратора?

### ISSUE THREAD

**Issue by Kristinita** [nnCron/nnCron#4]
### Цель

Автоматическое еженедельное обновление всех моих модулей и программ. 
### Попытки решения.

Написал следующий файл с расширением `.bat`:

``` shell
start cup all -y
start npm update -g --depth=0
start pip-review --local --interactive
start gem update
start cpan-outdated -p | cpanm
```

Чтобы запустить «батник» от имени администратора, необходимо создать ему ярлык, прописать в ярлыке запуск от имени администратора и запускать ярлык.
### Проблема

Не могу настроить в nnCron запуск ярлыка, а не самого `bat`-файла.
### Программно-аппаратное окружение

**Операционная система**
Windows 10.0.14393
**nnCron**
1.93b15

Спасибо.

**Comment by ruv** [comment]
Рецепт запуск от имени другого пользователя см. в разделе [Авторизация](http://www.nncron.ru/help/RU/working/task/authorization.htm) [документации](http://www.nncron.ru/help/help_ru.htm).
Что касается запуска ярлыка, попробуйте через `cmd.exe /c name.lnk`
